from __future__ import annotations

import html
from pathlib import Path
from typing import List

from .models import TradePlan
from .snapshot_store import load_snapshots


def _risk_level(plan: TradePlan) -> str:
    if any("清仓" in risk.action or "退出" in risk.action for risk in plan.risk_actions):
        return "高"
    if plan.risk_actions:
        return "中"
    return "低"


def write_daily_close_report(path: Path, snapshot_path: Path, plans: List[TradePlan], title: str = "每日收盘报告") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    snapshots = {item.symbol: item for item in load_snapshots(snapshot_path)}
    total = len(plans)
    buy_candidates = sum(1 for plan in plans if "买入候选" in plan.action)
    risk_count = sum(1 for plan in plans if plan.risk_actions)
    avg_score = sum(plan.score for plan in plans) / total if total else 0
    market_regime = plans[0].market_regime.value if plans else "未知"

    rows = []
    for plan in plans:
        snapshot = snapshots.get(plan.symbol)
        tags = "；".join(snapshot.tags) if snapshot else ""
        close = snapshot.close if snapshot else ""
        pct_change = round(snapshot.pct_change, 2) if snapshot else ""
        rows.append(f"""
          <tr>
            <td>{html.escape(plan.symbol)}</td>
            <td>{html.escape(plan.name)}</td>
            <td>{close}</td>
            <td>{pct_change}%</td>
            <td>{html.escape(plan.market_regime.value)}</td>
            <td>{html.escape(plan.action)}</td>
            <td>{plan.suggested_position_pct}%</td>
            <td>{plan.score}</td>
            <td>{html.escape(_risk_level(plan))}</td>
            <td>{html.escape(tags)}</td>
          </tr>
        """)

    cards = [
        ("市场状态", market_regime),
        ("股票数量", str(total)),
        ("买入候选", str(buy_candidates)),
        ("风控命中", str(risk_count)),
        ("平均分数", f"{avg_score:.1f}"),
    ]
    card_html = "\n".join(f"<div class=\"card\"><span>{label}</span><strong>{value}</strong></div>" for label, value in cards)

    body = f"""<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{html.escape(title)}</title>
  <style>
    :root {{
      --bg: #f6f7fb;
      --surface: #ffffff;
      --ink: #172033;
      --muted: #667085;
      --rule: #e5e7eb;
      --accent: #355cff;
      --danger: #c2410c;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font-family: "Microsoft YaHei", "PingFang SC", system-ui, sans-serif;
      line-height: 1.6;
    }}
    main {{ max-width: 1180px; margin: 0 auto; padding: 32px 20px 48px; }}
    header {{ margin-bottom: 24px; }}
    h1 {{ margin: 0 0 8px; font-size: 28px; }}
    .subtitle {{ color: var(--muted); margin: 0; }}
    .cards {{ display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 12px; margin: 22px 0; }}
    .card {{ background: var(--surface); border: 1px solid var(--rule); border-radius: 14px; padding: 16px; }}
    .card span {{ display: block; color: var(--muted); font-size: 13px; }}
    .card strong {{ display: block; color: var(--accent); font-size: 24px; margin-top: 4px; }}
    .panel {{ background: var(--surface); border: 1px solid var(--rule); border-radius: 14px; overflow: hidden; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th, td {{ padding: 12px 10px; border-bottom: 1px solid var(--rule); text-align: left; vertical-align: top; }}
    th {{ background: #f9fafb; color: var(--muted); font-weight: 600; white-space: nowrap; }}
    tr:last-child td {{ border-bottom: none; }}
    td:nth-child(6), td:nth-child(9) {{ font-weight: 600; }}
    .note {{ margin-top: 16px; color: var(--muted); font-size: 13px; }}
    @media (max-width: 900px) {{
      .cards {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
      .panel {{ overflow-x: auto; }}
      table {{ min-width: 980px; }}
    }}
  </style>
</head>
<body>
  <main>
    <header>
      <h1>{html.escape(title)}</h1>
      <p class="subtitle">基于最新行情快照和交易计划自动生成，仅用于复盘和规则验证。</p>
    </header>
    <section class="cards">{card_html}</section>
    <section class="panel">
      <table>
        <thead>
          <tr>
            <th>代码</th><th>名称</th><th>收盘</th><th>涨跌幅</th><th>市场</th>
            <th>建议动作</th><th>仓位</th><th>分数</th><th>风险</th><th>标签</th>
          </tr>
        </thead>
        <tbody>{''.join(rows)}</tbody>
      </table>
    </section>
    <p class="note">提示：若指南针活跃市值更新，需先运行 update-market，再重新生成本报告。</p>
  </main>
</body>
</html>
"""
    path.write_text(body, encoding="utf-8")
